#!/usr/bin/env python3
"""Build docs/superskills/kb-index.md from ADRs, specs, plans, pattern debt, compound wiki, and aliases.

Standard library only. This is intentionally a lightweight structured index,
not a semantic database.
"""
from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path

CLAIM_RE = re.compile(r"^\s*(CLAIM|EVIDENCE|SOURCE|SCOPE|RESIDUAL RISK)\s*:\s*(.+)", re.I)
HEADING_RE = re.compile(r"^(#{1,4})\s+(.+?)\s*$")
TOKEN_RE = re.compile(r"[A-Za-z][A-Za-z0-9_-]{2,}")
ALIAS_SECTION_RE = re.compile(r"^##\s+Synonyms\s*/\s*Alias Map", re.I)

STOP = {
    "the", "and", "for", "with", "from", "that", "this", "into", "when", "where", "which", "what", "have", "has", "had",
    "not", "are", "was", "were", "will", "would", "should", "could", "can", "cannot", "must", "use", "using", "docs",
    "superskills", "markdown", "status", "source", "scope", "claim", "evidence", "residual", "risk"
}

@dataclass
class Entry:
    topic: str
    kind: str
    path: str
    line: int
    summary: str
    fields: dict[str, str] = field(default_factory=dict)


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def rel(path: Path, root: Path) -> str:
    try:
        return str(path.relative_to(root))
    except ValueError:
        return str(path)


def normalize_topic(text: str) -> str:
    text = re.sub(r"[`*_#:\[\]()]", " ", text)
    words = [w.lower() for w in TOKEN_RE.findall(text)]
    words = [w for w in words if w not in STOP and not w.isdigit()]
    if not words:
        return "misc"
    # Prefer compact first two meaningful words.
    return " ".join(words[:3])


def parse_aliases(context: Path) -> dict[str, list[str]]:
    aliases: dict[str, list[str]] = {}
    if not context.exists():
        return aliases
    lines = read(context).splitlines()
    in_section = False
    for line in lines:
        if ALIAS_SECTION_RE.search(line):
            in_section = True
            continue
        if in_section and line.startswith("## "):
            break
        if not in_section:
            continue
        m = re.match(r"\s*[-*]?\s*([^:]+):\s*(.+)", line)
        if m:
            key = m.group(1).strip().strip("`*").lower()
            vals = [v.strip().strip("`*") for v in re.split(r",|;", m.group(2)) if v.strip()]
            aliases[key] = vals
    return aliases


def classify(path: Path) -> str:
    parts = set(path.parts)
    name = path.name.lower()
    if "adrs" in parts or name == "adr.md":
        return "ADR"
    if "specs" in parts or "blueprint" in name or "contracts" in name:
        return "SPEC"
    if "plans" in parts:
        return "PLAN"
    if name == "pattern-debt.md":
        return "PATTERN-DEBT"
    if name == "compound-wiki.md":
        return "COMPOUND"
    if name == "context.md":
        return "CONTEXT"
    if name == "qbr-calibration.md":
        return "CALIBRATION"
    return "KB"


def collect_entries(root: Path, kb: Path) -> list[Entry]:
    entries: list[Entry] = []
    paths = [p for p in sorted(kb.rglob("*.md")) if p.name != "kb-index.md"]
    for path in paths:
        lines = read(path).splitlines()
        pending_fields: dict[str, str] = {}
        for i, line in enumerate(lines, 1):
            fm = CLAIM_RE.match(line)
            if fm:
                key = fm.group(1).upper()
                val = fm.group(2).strip()
                pending_fields[key] = val
                if key == "CLAIM":
                    entries.append(Entry(normalize_topic(val), classify(path), rel(path, root), i, val[:180], {"CLAIM": val}))
                continue
            hm = HEADING_RE.match(line)
            if hm:
                title = hm.group(2).strip()
                if title.lower() not in {"gotchas", "overview", "process", "output"}:
                    entries.append(Entry(normalize_topic(title), classify(path), rel(path, root), i, title[:180], {}))
                continue
            if "PATTERN-DEBT" in line or "ADR-" in line or "ASSUMED" in line or "LAST CONFIRMED" in line:
                entries.append(Entry(normalize_topic(line), classify(path), rel(path, root), i, line.strip()[:180], {}))
    return entries


def render(root: Path, aliases: dict[str, list[str]], entries: list[Entry]) -> str:
    by_topic: dict[str, list[Entry]] = defaultdict(list)
    for e in entries:
        by_topic[e.topic].append(e)

    out: list[str] = []
    out.append("# Super Skills KB Index")
    out.append("")
    out.append("Generated by `tools/build_kb_index.py`. Do not hand-edit generated sections; update source ADRs/specs/CONTEXT/Gotchas instead.")
    out.append("")
    out.append("## Alias Map")
    out.append("")
    if aliases:
        for key in sorted(aliases):
            out.append(f"- **{key}**: {', '.join(aliases[key])}")
    else:
        out.append("- No aliases found. Add `## Synonyms / Alias Map` to `docs/superskills/CONTEXT.md`.")
    out.append("")
    out.append("## Topics")
    out.append("")
    for topic in sorted(by_topic):
        refs = by_topic[topic][:12]
        out.append(f"### {topic}")
        for e in refs:
            out.append(f"- [{e.kind}] `{e.path}:{e.line}` — {e.summary}")
        if len(by_topic[topic]) > len(refs):
            out.append(f"- ... {len(by_topic[topic]) - len(refs)} more")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description="Build Super Skills KB topic index")
    ap.add_argument("root", nargs="?", default=".", help="project root containing docs/superskills")
    ap.add_argument("--check", action="store_true", help="fail if generated output differs")
    args = ap.parse_args()
    root = Path(args.root).resolve()
    kb = root / "docs" / "superskills"
    if not kb.exists():
        print("KB not initialized — docs/superskills not found")
        return 0
    out_path = kb / "kb-index.md"
    aliases = parse_aliases(kb / "CONTEXT.md")
    entries = collect_entries(root, kb)
    rendered = render(root, aliases, entries)
    if args.check:
        current = read(out_path) if out_path.exists() else ""
        if current != rendered:
            print(f"kb-index out of date: {out_path}")
            return 1
        print(f"kb-index up to date: {out_path}")
        return 0
    out_path.write_text(rendered, encoding="utf-8")
    print(f"wrote {out_path} ({len(entries)} entries, {len(aliases)} aliases)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
