import { z } from "zod/v4";
import fs from "node:fs/promises";
import path from "node:path";
import { skillsBasePath } from "../skills/skill_loader.js";
import type { ToolDefinition } from "../mcp/adapter/tool_registry.js";

function kbBasePath(): string {
  const base = path.resolve(skillsBasePath(), "..", "..");
  return path.join(base, "docs", "superskills");
}

async function ensureKbDir(): Promise<string> {
  const dir = kbBasePath();
  await fs.mkdir(dir, { recursive: true });
  return dir;
}

const KB_ENTRY_CATEGORIES = ["gotcha", "pattern-debt", "domain-term", "decision", "bug-pattern"] as const;

const kbWriteTool: ToolDefinition = {
  name: "kb_write",
  description:
    "Write a single knowledge entry to the project's persistent knowledge base. " +
    "Use this after discovering a gotcha, bug pattern, domain term, or architectural decision. " +
    "Entries accumulate across sessions and are injected into future skill_run responses.",
  inputSchema: {
    category: z
      .enum(KB_ENTRY_CATEGORIES)
      .describe("The type of knowledge being recorded."),
    slug: z
      .string()
      .describe("Unique kebab-case identifier for this entry (e.g. 'async-no-await', 'user-means-tenant')."),
    content: z
      .string()
      .describe("The knowledge content. For gotchas: what happened and what to do instead. For terms: definition. For decisions: context + decision + consequences."),
    source: z
      .enum(["direct-observation", "code-review", "incident", "retrospective", "audit"])
      .optional()
      .describe("How this knowledge was discovered. Default: direct-observation."),
    shareable: z
      .boolean()
      .optional()
      .describe("Whether this entry can be included in anonymized cross-project telemetry. Default: false."),
  },
  allowedPhases: ["intake", "execution", "review", "completed"],
  capabilities: ["fs.write"],
  annotations: {
    readOnlyHint: false,
    destructiveHint: false,
    idempotentHint: true,
    openWorldHint: false,
  },
  execution: {
    taskSupport: "forbidden",
  },
  handler: async (args) => {
    const {
      category,
      slug,
      content,
      source = "direct-observation",
      shareable = false,
    } = args as {
      category: string;
      slug: string;
      content: string;
      source?: string;
      shareable?: boolean;
    };

    const dir = await ensureKbDir();
    const filePath = path.join(dir, `${category}.md`);

    const date = new Date().toISOString().slice(0, 10);
    const entryId = `KB-${category.toUpperCase()}-${slug}`;

    let existing = "";
    try {
      existing = await fs.readFile(filePath, "utf-8");
    } catch { /* file may not exist yet */ }

    if (existing.includes(entryId)) {
      return {
        content: [{ type: "text", text: `[kb_write] Entry ${entryId} already exists. Use a different slug or update manually.` }],
      };
    }

    const entry = [
      `\n### ${entryId}`,
      `- **date:** ${date}`,
      `- **source:** ${source}`,
      `- **shareable:** ${shareable}`,
      `- **content:** ${content}`,
      "",
    ].join("\n");

    if (!existing) {
      const header = `# Knowledge Base — ${category}\n\nAuto-generated by kb_write. Do not edit header.\n`;
      await fs.writeFile(filePath, header + entry, "utf-8");
    } else {
      await fs.appendFile(filePath, entry, "utf-8");
    }

    return {
      content: [{ type: "text", text: `[kb_write] Recorded ${entryId} in ${category}.md (${date}, source: ${source}).` }],
    };
  },
};

const kbQueryTool: ToolDefinition = {
  name: "kb_query",
  description:
    "Search the project's persistent knowledge base for entries matching a query. " +
    "Returns matching gotchas, patterns, terms, and decisions across all categories.",
  inputSchema: {
    query: z
      .string()
      .describe("Search term: topic, module name, slug, or keyword."),
    category: z
      .enum([...KB_ENTRY_CATEGORIES, "all"])
      .optional()
      .describe("Filter to a specific category. Default: 'all'."),
  },
  allowedPhases: ["intake", "execution", "review", "completed"],
  capabilities: ["fs.read"],
  annotations: {
    readOnlyHint: true,
    destructiveHint: false,
    idempotentHint: true,
    openWorldHint: false,
  },
  execution: {
    taskSupport: "forbidden",
  },
  handler: async (args) => {
    const { query, category = "all" } = args as { query: string; category?: string };
    const dir = kbBasePath();

    const categories = category === "all"
      ? [...KB_ENTRY_CATEGORIES]
      : [category];

    const results: string[] = [];
    const queryLower = query.toLowerCase();

    for (const cat of categories) {
      try {
        const content = await fs.readFile(path.join(dir, `${cat}.md`), "utf-8");
        const entries = content.split(/(?=^### KB-)/m);
        for (const entry of entries) {
          if (entry.toLowerCase().includes(queryLower)) {
            results.push(entry.trim());
          }
        }
      } catch { /* file doesn't exist for this category */ }
    }

    if (results.length === 0) {
      return {
        content: [{ type: "text", text: `[kb_query] No entries found for "${query}" in ${category === "all" ? "any category" : category}.` }],
      };
    }

    return {
      content: [{ type: "text", text: `[kb_query] ${results.length} result(s) for "${query}":\n\n${results.join("\n\n")}` }],
    };
  },
};

const kbHealthTool: ToolDefinition = {
  name: "kb_health",
  description:
    "Check epistemic health of the project's knowledge base: count entries by category, " +
    "flag stale entries (older than 90 days), report coverage gaps.",
  inputSchema: {},
  allowedPhases: ["intake", "execution", "review", "completed"],
  capabilities: ["fs.read"],
  annotations: {
    readOnlyHint: true,
    destructiveHint: false,
    idempotentHint: true,
    openWorldHint: false,
  },
  execution: {
    taskSupport: "forbidden",
  },
  handler: async () => {
    const dir = kbBasePath();
    const report: string[] = ["KNOWLEDGE BASE HEALTH REPORT", "=".repeat(40)];
    const today = new Date();
    let totalEntries = 0;
    let staleCount = 0;

    for (const cat of KB_ENTRY_CATEGORIES) {
      try {
        const content = await fs.readFile(path.join(dir, `${cat}.md`), "utf-8");
        const entries = content.split(/(?=^### KB-)/m).filter(e => e.startsWith("### KB-"));
        totalEntries += entries.length;

        const staleEntries: string[] = [];
        for (const entry of entries) {
          const dateMatch = entry.match(/\*\*date:\*\*\s*(\d{4}-\d{2}-\d{2})/);
          if (dateMatch) {
            const entryDate = new Date(dateMatch[1]);
            const daysOld = Math.floor((today.getTime() - entryDate.getTime()) / (1000 * 60 * 60 * 24));
            if (daysOld > 90) {
              const idMatch = entry.match(/### (KB-[A-Z-]+-[a-z0-9-]+)/);
              staleEntries.push(`${idMatch?.[1] ?? "unknown"} (${daysOld} days old)`);
              staleCount++;
            }
          }
        }

        report.push(`\n${cat}: ${entries.length} entries`);
        if (staleEntries.length > 0) {
          report.push(`  STALE (>90 days): ${staleEntries.join(", ")}`);
        }
      } catch {
        report.push(`\n${cat}: no entries (file missing)`);
      }
    }

    report.push(`\nTotal: ${totalEntries} entries, ${staleCount} stale`);

    const missing: string[] = [];
    for (const cat of KB_ENTRY_CATEGORIES) {
      try {
        await fs.access(path.join(dir, `${cat}.md`));
      } catch {
        missing.push(cat);
      }
    }
    if (missing.length > 0) {
      report.push(`Coverage gaps: no entries for ${missing.join(", ")}`);
    }

    return {
      content: [{ type: "text", text: report.join("\n") }],
    };
  },
};

const knowledgeTools: ToolDefinition[] = [
  kbWriteTool,
  kbQueryTool,
  kbHealthTool,
];

export default knowledgeTools;
