import { z } from "zod/v4";
import fs from "node:fs/promises";
import path from "node:path";
import { skillsBasePath } from "../skills/skill_loader.js";
import { clearProjectContextCache } from "../skills/skill_executor.js";
import type { ToolDefinition } from "../mcp/adapter/tool_registry.js";

function kbBasePath(): string {
  const base = path.resolve(skillsBasePath(), "..", "..");
  return path.join(base, "docs", "superskills");
}

async function ensureKbDir(): Promise<string> {
  const dir = kbBasePath();
  await fs.mkdir(dir, { recursive: true });
  return dir;
}

const KB_ENTRY_CATEGORIES = ["gotcha", "pattern-debt", "domain-term", "decision", "bug-pattern"] as const;

const kbWriteTool: ToolDefinition = {
  name: "kb_write",
  description:
    "Write a single knowledge entry to the project's persistent knowledge base. " +
    "Use this after discovering a gotcha, bug pattern, domain term, or architectural decision. " +
    "Entries accumulate across sessions and are injected into future skill_run responses.",
  inputSchema: {
    category: z
      .enum(KB_ENTRY_CATEGORIES)
      .describe("The type of knowledge being recorded."),
    slug: z
      .string()
      .min(1)
      .max(80)
      .regex(
        /^[a-z0-9]+(?:-[a-z0-9]+)*$/,
        "slug must be kebab-case: lowercase letters/digits separated by single hyphens (e.g. 'async-no-await').",
      )
      .describe("Unique kebab-case identifier for this entry (e.g. 'async-no-await', 'user-means-tenant')."),
    content: z
      .string()
      .describe("The knowledge content. For gotchas: what happened and what to do instead. For terms: definition. For decisions: context + decision + consequences."),
    source: z
      .enum(["direct-observation", "code-review", "incident", "retrospective", "audit"])
      .optional()
      .describe("How this knowledge was discovered. Default: direct-observation."),
    shareable: z
      .boolean()
      .optional()
      .describe("Whether this entry can be included in anonymized cross-project telemetry. Default: false."),
  },
  allowedPhases: ["intake", "execution", "review", "completed"],
  capabilities: ["kb.write"],
  annotations: {
    readOnlyHint: false,
    destructiveHint: false,
    idempotentHint: true,
    openWorldHint: false,
  },
  execution: {
    taskSupport: "forbidden",
  },
  handler: async (args) => {
    const {
      category,
      slug,
      content,
      source = "direct-observation",
      shareable = false,
    } = args as {
      category: string;
      slug: string;
      content: string;
      source?: string;
      shareable?: boolean;
    };

    const dir = await ensureKbDir();
    const filePath = path.join(dir, `${category}.md`);

    const date = new Date().toISOString().slice(0, 10);
    const entryId = `KB-${category.toUpperCase()}-${slug}`;

    let existing = "";
    try {
      existing = await fs.readFile(filePath, "utf-8");
    } catch { /* file may not exist yet */ }

    if (existing.includes(entryId)) {
      return {
        content: [{ type: "text", text: `[kb_write] Entry ${entryId} already exists. Use a different slug or update manually.` }],
      };
    }

    const entry = [
      `\n### ${entryId}`,
      `- **date:** ${date}`,
      `- **source:** ${source}`,
      `- **shareable:** ${shareable}`,
      `- **content:** ${content}`,
      "",
    ].join("\n");

    if (!existing) {
      const header = `# Knowledge Base — ${category}\n\nAuto-generated by kb_write. Do not edit header.\n`;
      await fs.writeFile(filePath, header + entry, "utf-8");
    } else {
      await fs.appendFile(filePath, entry, "utf-8");
    }

    clearProjectContextCache();

    return {
      content: [{ type: "text", text: `[kb_write] Recorded ${entryId} in ${category}.md (${date}, source: ${source}).` }],
    };
  },
};

const kbQueryTool: ToolDefinition = {
  name: "kb_query",
  description:
    "Search the project's persistent knowledge base for entries matching a query. " +
    "By default returns a compact summary (id + first content line) per match. " +
    "Set detail=true to fetch the full entry bodies (use after narrowing by id).",
  inputSchema: {
    query: z
      .string()
      .describe("Search term: topic, module name, slug, or keyword."),
    category: z
      .enum([...KB_ENTRY_CATEGORIES, "all"])
      .optional()
      .describe("Filter to a specific category. Default: 'all'."),
    detail: z
      .boolean()
      .optional()
      .describe("If true, return the full entry body for every match. Default: false (summary only)."),
    limit: z
      .number()
      .int()
      .min(1)
      .max(100)
      .optional()
      .describe("Maximum entries to return. Default: 20."),
  },
  allowedPhases: ["intake", "execution", "review", "completed"],
  capabilities: ["fs.read"],
  annotations: {
    readOnlyHint: true,
    destructiveHint: false,
    idempotentHint: true,
    openWorldHint: false,
  },
  execution: {
    taskSupport: "forbidden",
  },
  handler: async (args) => {
    const { query, category = "all", detail = false, limit = 20 } = args as {
      query: string;
      category?: string;
      detail?: boolean;
      limit?: number;
    };
    const dir = kbBasePath();

    const categories = category === "all"
      ? [...KB_ENTRY_CATEGORIES]
      : [category];

    interface KbMatch { id: string; summary: string; full: string; }
    const matches: KbMatch[] = [];
    const queryLower = query.toLowerCase();

    for (const cat of categories) {
      try {
        const content = await fs.readFile(path.join(dir, `${cat}.md`), "utf-8");
        const entries = content.split(/(?=^### KB-)/m);
        for (const entry of entries) {
          if (!entry.startsWith("### KB-")) continue;
          if (!entry.toLowerCase().includes(queryLower)) continue;
          const idMatch = entry.match(/^### (KB-[A-Z-]+-[a-z0-9-]+)/);
          const contentMatch = entry.match(/\*\*content:\*\*\s*(.+)/);
          const summary = (contentMatch?.[1] ?? "").trim().slice(0, 140);
          matches.push({
            id: idMatch?.[1] ?? "KB-UNKNOWN",
            summary,
            full: entry.trim(),
          });
        }
      } catch { /* file doesn't exist for this category */ }
    }

    if (matches.length === 0) {
      return {
        content: [{ type: "text", text: `[kb_query] No entries found for "${query}" in ${category === "all" ? "any category" : category}.` }],
      };
    }

    const truncated = matches.slice(0, limit);
    const overflow = matches.length - truncated.length;

    if (detail) {
      const body = truncated.map(m => m.full).join("\n\n");
      const note = overflow > 0 ? `\n\n[kb_query] ${overflow} additional match(es) omitted (limit=${limit}).` : "";
      return {
        content: [{ type: "text", text: `[kb_query] ${truncated.length} result(s) for "${query}" (detail=true):\n\n${body}${note}` }],
      };
    }

    const summaryLines = truncated.map(m => `- ${m.id}: ${m.summary}`);
    const tip = `\n\nUse detail=true (and optionally narrow query to an id) to fetch full bodies.`;
    const note = overflow > 0 ? `\n[kb_query] ${overflow} additional match(es) omitted (limit=${limit}).` : "";
    return {
      content: [{
        type: "text",
        text: `[kb_query] ${truncated.length} result(s) for "${query}" (summary):\n${summaryLines.join("\n")}${note}${tip}`,
      }],
    };
  },
};

const kbHealthTool: ToolDefinition = {
  name: "kb_health",
  description:
    "Check epistemic health of the project's knowledge base: count entries by category, " +
    "flag stale entries (older than 90 days), report coverage gaps.",
  inputSchema: {},
  allowedPhases: ["intake", "execution", "review", "completed"],
  capabilities: ["fs.read"],
  annotations: {
    readOnlyHint: true,
    destructiveHint: false,
    idempotentHint: true,
    openWorldHint: false,
  },
  execution: {
    taskSupport: "forbidden",
  },
  handler: async () => {
    const dir = kbBasePath();
    const report: string[] = ["KNOWLEDGE BASE HEALTH REPORT", "=".repeat(40)];
    const today = new Date();
    let totalEntries = 0;
    let staleCount = 0;

    for (const cat of KB_ENTRY_CATEGORIES) {
      try {
        const content = await fs.readFile(path.join(dir, `${cat}.md`), "utf-8");
        const entries = content.split(/(?=^### KB-)/m).filter(e => e.startsWith("### KB-"));
        totalEntries += entries.length;

        const staleEntries: string[] = [];
        for (const entry of entries) {
          const dateMatch = entry.match(/\*\*date:\*\*\s*(\d{4}-\d{2}-\d{2})/);
          if (dateMatch) {
            const entryDate = new Date(dateMatch[1]);
            const daysOld = Math.floor((today.getTime() - entryDate.getTime()) / (1000 * 60 * 60 * 24));
            if (daysOld > 90) {
              const idMatch = entry.match(/### (KB-[A-Z-]+-[a-z0-9-]+)/);
              staleEntries.push(`${idMatch?.[1] ?? "unknown"} (${daysOld} days old)`);
              staleCount++;
            }
          }
        }

        report.push(`\n${cat}: ${entries.length} entries`);
        if (staleEntries.length > 0) {
          report.push(`  STALE (>90 days): ${staleEntries.join(", ")}`);
        }
      } catch {
        report.push(`\n${cat}: no entries (file missing)`);
      }
    }

    report.push(`\nTotal: ${totalEntries} entries, ${staleCount} stale`);

    const missing: string[] = [];
    for (const cat of KB_ENTRY_CATEGORIES) {
      try {
        await fs.access(path.join(dir, `${cat}.md`));
      } catch {
        missing.push(cat);
      }
    }
    if (missing.length > 0) {
      report.push(`Coverage gaps: no entries for ${missing.join(", ")}`);
    }

    return {
      content: [{ type: "text", text: report.join("\n") }],
    };
  },
};

const kbUpdateTool: ToolDefinition = {
  name: "kb_update",
  description:
    "Update an existing knowledge base entry by slug. " +
    "Use when a gotcha, decision, or bug pattern has changed and the old record is stale. " +
    "Replaces the matching entry in-place; preserves all other entries.",
  inputSchema: {
    category: z
      .enum(KB_ENTRY_CATEGORIES)
      .describe("The category of the entry to update."),
    slug: z
      .string()
      .min(1)
      .max(80)
      .regex(
        /^[a-z0-9]+(?:-[a-z0-9]+)*$/,
        "slug must be kebab-case.",
      )
      .describe("The slug of the entry to update (must already exist)."),
    content: z
      .string()
      .describe("The new content to replace the existing entry with."),
    source: z
      .enum(["direct-observation", "code-review", "incident", "retrospective", "audit"])
      .optional()
      .describe("Updated source. Default: direct-observation."),
  },
  allowedPhases: ["intake", "execution", "review", "completed"],
  capabilities: ["kb.write"],
  annotations: {
    readOnlyHint: false,
    destructiveHint: false,
    idempotentHint: true,
    openWorldHint: false,
  },
  execution: {
    taskSupport: "forbidden",
  },
  handler: async (args) => {
    const {
      category,
      slug,
      content,
      source = "direct-observation",
    } = args as {
      category: string;
      slug: string;
      content: string;
      source?: string;
    };

    const dir = await ensureKbDir();
    const filePath = path.join(dir, `${category}.md`);
    const entryId = `KB-${category.toUpperCase()}-${slug}`;
    const date = new Date().toISOString().slice(0, 10);

    let existing = "";
    try {
      existing = await fs.readFile(filePath, "utf-8");
    } catch {
      return {
        content: [{ type: "text", text: `[kb_update] Entry ${entryId} not found — category file does not exist. Use kb_write to create it.` }],
      };
    }

    if (!existing.includes(entryId)) {
      return {
        content: [{ type: "text", text: `[kb_update] Entry ${entryId} not found. Use kb_write to create a new entry.` }],
      };
    }

    const newEntry = [
      `\n### ${entryId}`,
      `- **date:** ${date}`,
      `- **source:** ${source}`,
      `- **shareable:** false`,
      `- **content:** ${content}`,
      "",
    ].join("\n");

    // Split on entry boundaries, replace the matching entry
    const parts = existing.split(/(?=\n### KB-)/);
    const updated = parts.map(part =>
      part.includes(entryId) ? newEntry : part
    ).join("");

    await fs.writeFile(filePath, updated, "utf-8");
    clearProjectContextCache();

    return {
      content: [{ type: "text", text: `[kb_update] Updated ${entryId} in ${category}.md (${date}, source: ${source}).` }],
    };
  },
};

const knowledgeTools: ToolDefinition[] = [
  kbWriteTool,
  kbQueryTool,
  kbHealthTool,
  kbUpdateTool,
];

export default knowledgeTools;
